version: "3.7"
services:
  app:
    build:
      args:
        user: bugzee
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: pins
    container_name: pins-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - pins

  db:
    image: mysql:8.0.27
    container_name: pins-db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_HOST: '%'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    networks:
      - pins

  nginx:
    image: nginx:alpine
    container_name: pins-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - pins

networks:
  pins:
    driver: bridge
